version: '3'
services:
  github_webhook_server:
    build: .
    container_name: github_webhook_server
    ports:
      - "6900:6900"
    volumes:
      - ./:/app
    command: python3 /app/webhook_server.py --host 0.0.0.0 --port 6900 'echo yes!'
